### ISSUE TITLE
Child form  - school button and "Odustani" button

### ISSUE THREAD

**Issue by shomy4** [shomy4/SuperKamp#3]
1.School field should take values from school table as it is now available.

2. Discussion whether "Odustani" button should point to the list view of that object?
Example for school create and update view
```
<script type="text/javascript">
function goBack() {
	window.location.href = "{% url 'mentors:school_list' %}";
}
</script>
```

![child_form](https://cloud.githubusercontent.com/assets/10053236/16358008/eaf485bc-3b06-11e6-8de9-5755eddfa883.png)

**Comment by burlicconi** [comment]
E, covek, bio sam bas danas u NS-u kod drugarice koja mi je nabacila
sljaku. Kaze Toma je odgovorio sve sa da na moja pitanja, a koliko sam
shvatio, oni se slazu nacelno sa svime sto mi predlozimo.

To znaci da vazi ono "ubaci razumnu pretpostavku i tako realizuj". Videcu s
njima samo ono nekih specijalnih viewa da ubacimo, ali ovo sve do sada ce
da pije vodu.

Ako nesto nisi suguran, a nije realizovano, vidi kako bi bilo najlogicnije
pa tako uradi i tako cemo ubuduce ako bude nesto slicno.

Pozdrav!
25.06.2016. 19.01, "Miloš Miletić" <notifications@github.com> је написао/ла:

**Comment by shomy4** [comment]
Closed as autocomplete select input has been implementded.
